798679 - Read correct argument
This opt_arg variable has been renamed in 85bafb2 and this is left over.

addressing:
  File "/usr/lib/python2.6/site-packages/mock-0.8.0rc1-py2.6.egg/mock.py", line 857, in assert_called_with
    raise AssertionError(msg)
AssertionError: Expected call: mock('ACME_Corporation', 'Library')
Actual call: mock('ACME_Corporation', None)