Revert "R0201: 30,4:KatelloAPI.server: Method could be a function"
This reverts commit a6f761cf203e96386f39740febe2f4a76f6e4c59.

property and classmethod does not like each other:
addressing:
2012-08-28 08:20:28,704 [ERROR][MainThread] error() @ base.py:180 - Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/katello/client/cli/base.py", line 190, in main
    ret_code = super(KatelloCLI, self).main(args, command_name, parent_usage)
  File "/usr/lib/python2.6/site-packages/katello/client/core/base.py", line 293, in main
    return subcommand.main(self.args[1:], self.args[0], self._get_usage_line(command_name, parent_usage))
  File "/usr/lib/python2.6/site-packages/katello/client/core/base.py", line 293, in main
    return subcommand.main(self.args[1:], self.args[0], self._get_usage_line(command_name, parent_usage))
  File "/usr/lib/python2.6/site-packages/katello/client/core/base.py", line 368, in main
    return self.run()
  File "/usr/lib/python2.6/site-packages/katello/client/core/user.py", line 91, in run
    user = self.api.create(username, password, email, disabled, environment, default_locale)
  File "/usr/lib/python2.6/site-packages/katello/client/api/user.py", line 36, in create
    return self.server.POST(path, userdata)[1]
TypeError: 'classmethod' object is not callable